import React, { Component } from 'react'
import Footer from './Footer';

export default class History extends Component {
    render() {
        return (
            <div className="history-page">
                <div className='history'>
                    <div className="history-text">
                    <h1>UISCE BEATHA:</h1>
                    <h3>Gaelic meaning Whiskey</h3> 
                    </div>
                </div>

                <div className="history-article">
                <p>The influence of alcohol had a great effect on the development of the human civilization. As the wine, crated over 8 thousand years ago managed to infuse itself into many religions and customs over the world, whisky managed to became synonym of a Scottish history and one of the most popular modern alcoholic beverages. Although the national drink of the Scots gained worldwide popularity after 15th century, the origin of whisky can be traced to much older periods of our history.</p>

                <p>Whisky is made via distillation of fermented grain and first records of that process was found in the archeological digs of millennia BC Babylon and Mesopotamia. Initially used for creation of perfumes and aromas, distillation 2nd slowly spread across the ancient civilizations where it received numerous adaptations and improvements, finally finding its home behind the walls of the European Christian monasteries. Stability of their order and the need to produce several types of alcoholic beverages that were used is several of their religious ceremonies preserved the process of fermentation and distillation during the harsh times of dark and middle ages. It is believed that distillation came to the areas of Ireland and Scotland between 11th and 13th century with Christian monks, but some records show that Ancient Celts practiced distillation during the production of their "uisgebeatha" (water of life). Low access to grapes was one of the deciding factors in the popularization of beer and whisky in northern Europe. Through the decades of perfecting the process of distillation, Scotts soon become the world leaders in production of quality whisky. By the time the first written record of whisky appeared in 1494, production and consumption of whisky in Scotland have already reached mass appeal. In that historic record, Friar John Cor received "eight bolls of malt to make aqua vitae", which was enough for the production of around 1500 bottles of whisky.</p>

                <p>Popularity of whisky continued to grew during the early years of 16th century, until 1541 when English King Henry VIII dissolved monasteries in Scotland. This event forced newly unemployed monks to start private production of whisky, and they soon spread their knowledge across entire Scotland. In the beginning of the 18th century, Scott's love toward the whisky would be put to test again when English crown merged with the Scotland and imposed new harsh taxes on any unlicensed alcohol brewery. To combat this taxes which greatly reduced production of whisky in entire Northern Europe, Scottish brewers started producing their beverage illegally. Thousands secret distilleries started makingwhisky all across the northern England, often working only during night when low visibility hid the smokes from their fires (during this period whisky received his famous nickname "moonshine"). Smuggling of whisky soon became an art form, and numerous fights between smugglers and Scottish and English government officials fought daily for over 150 years. During the years of Scott's taxation, shortages of whisky around the world had great impact on several countries. Most notably, during American Revolutionwhisky became very scarce and was often used as a currency. Few years after end of the war, US Government repeated the same mistake as in Scotland and introduced heavy taxes on the ingredients, production and sales of whisky. This brought great dissatisfaction among US farm workers, who promptly started famous "Whisky Rebellion".</p>

                <p>End of the struggles for whisky makers in Scotland finally came in 1823, when English government introduced a law that enabled legalization of whisky production. This event rejuvenated whisky manufacturing across entire Scotland and Ireland, and drove new wave of technical innovation. One of the greatest inventions of that time was "continuous still" that was brought by Robert Stein (and later patented by	Aeneas Coffey). It enabled brewers to produce whisky much faster, and to make drink of higher quality.</p>

                <p>Second half of 19th century was marked by two important events. Scott Andrew Usher successfully perfected blended whisky, and managed to market it to the rest of the world making it one of the most successful alcoholic beverages. Another factor was the sudden spreading of the pest Phylloxera which managed to decimate worldwide production of wine. Faced with greatly reduced output of new wines, worldwide drinking population turned their attention to the whisky.</p>

                <p>The last big hit on the worldwide production of whisky happened during first half of 20th century. After few centuries of making whisky in North America (from 1823 they called it Bourbon), distilleries overnight become illegal when public pressure forced US government to ban sale, manufacturing, and transportation of alcohol between 1920 to 1933. During the period of Prohibitiondistilleries all around the US received crippling blow, and only very limited production of religious wines and medicinal whisky was allowed to remain. As with the 150 yearlong alcohol ban in Scotland, United States public soon began its own underground movement for production and transportation of alcohol. Rise of small crimes, formation of very organized criminal organization and public pressure brought the end of Prohibition in 1933, but the consumption of alcohol remained in pre-prohibition levels for the next three decades. Advancements within the alcohol industry were also severely crippled, and vast majority of pre-prohibition breweries were forced to shut down their businesses, which led to the closure of many taverns, mass loss of jobs and overall economic reversal. The effects of Prohibition had great impact on the culture of the US - heavy drinks rose in popularity (of the expense on previously popular beer and wine), and appearance of women drinkers in saloons and bars became socially acceptable.</p>

                <p>Popularity of whisky continues to grow with each passing year, and in 2009 Scottish brewers managed to export record breaking 1.1 billion bottles of whisky to the customers around the world.</p>
                </div>
            <Footer />
            </div>
        )
    }
}